project:
  type: website
  output-dir: docs

website:
  title: "StatShiny"
  navbar:
    left:
      - href: index.qmd
        text: Home
    tools:
      - icon: github
        href: https://github.com/stat-teaching/statshiny
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



